Feature/trac 10235
iterate-ch/cyberduck pull request #12582
Opened 2021-11-29 10:14 UTC by dkocher

Close #10235.

2021-11-29 10:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=12582) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=12582) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dkocher<br/>:x: bgkarthik27<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iterate-ch/cyberduck?pullRequest=12582) it.</sub>

2021-11-29 12:14 UTC, AliveDevil approved these changes

2021-11-29 12:14 UTC, AliveDevil commented on osx/src/main/java/ch/cyberduck/ui/cocoa/MainApplication.java
> +                    new FTPProtocol(),
Double-indent?

2021-11-29 12:16 UTC, AliveDevil requested changes

2021-11-29 12:16 UTC, AliveDevil commented on box/pom.xml
> +        <version>8.1.0-SNAPSHOT</version>
Rebase version 8.2.0-SNAPSHOT.

2021-11-29 16:01 UTC, AliveDevil approved these changes

2021-11-30 12:57 UTC, ylangisc approved these changes

2021-11-30 12:59 UTC, merged