Handle `=` character in property value.
iterate-ch/cyberduck pull request #12581
Opened 2021-11-29 10:09 UTC by dkocher

2021-11-29 10:24 UTC, AliveDevil commented on core/src/main/java/ch/cyberduck/core/Profile.java
> +                property -> 2 == StringUtils.split(property, "=", 2).length ? StringUtils.split(property, "=", 2)[0] : property,
StringUtils.FirstIndexOf and then Substring?

2021-11-29 12:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=12581) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=12581) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dkocher<br/>:x: ylangisc<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iterate-ch/cyberduck?pullRequest=12581) it.</sub>

2021-11-29 12:44 UTC, ylangisc requested changes
Added failing test.

2021-11-30 13:05 UTC, ylangisc approved these changes

2021-11-30 13:30 UTC, AliveDevil approved these changes

2021-11-30 13:39 UTC, merged