Contabo Object Storage profile added.
iterate-ch/cyberduck pull request #12956
Opened 2022-03-10 11:20 UTC by hoxsec

2022-03-10 11:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=12956) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=12956) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iterate-ch/cyberduck?pullRequest=12956) it.</sub>

2022-03-10 11:24 UTC, dkocher requested changes

2022-03-10 12:44 UTC, hoxsec commented on profiles/Contabo Object Storage (EU2).cyberduckprofile
> +        <string>eu2 (DE-Nuremberg)</string>
Thanks for the tip, now it should be good

![image](https://user-images.githubusercontent.com/6719066/157664398-7a74568d-f318-427f-a417-a6846c6e8b0d.png)

2022-03-14 08:11 UTC, dkocher approved these changes

2022-03-14 12:54 UTC, merged