Feature/freenet 31
iterate-ch/cyberduck pull request #13035
Opened 2022-04-01 08:44 UTC by dkocher

2022-04-01 09:47 UTC, AliveDevil commented on freenet/src/main/java/ch/cyberduck/core/freenet/FreenetSession.java
> +                    request.addHeader(new BasicHeader("X-Freenet-Insid", new MD5ChecksumCompute().compute(new MacUniqueIdService().getUUID()).hash));
Can we atlast use SHA256 and truncate to 24 bits of it?[^1]

[^1]: https://en.wikipedia.org/wiki/MAC_address_anonymization#Ali_&_Dyo_Approach

2022-04-01 10:08 UTC, AliveDevil requested changes

2022-04-01 10:08 UTC, AliveDevil commented on freenet/src/main/java/ch/cyberduck/core/freenet/FreenetSession.java
> +                    request.addHeader(new BasicHeader("X-Freenet-Insid", new MD5ChecksumCompute().compute(new MacUniqueIdService().getUUID()).hash));
Singleton value here? Doesn't need to compute checksum for every single request, as it will be static.

2022-04-05 07:28 UTC, ylangisc commented on freenet/src/main/java/ch/cyberduck/core/freenet/FreenetSession.java
> +        catch(LocalAccessDeniedException | ChecksumException e) {
Happens how often?

2022-04-07 06:37 UTC, ylangisc commented on freenet/src/main/java/ch/cyberduck/core/freenet/FreenetSession.java
> +            final String identifier = new MD5ChecksumCompute().compute(System.getProperty("user.name")).hash;
`System.getProperty("user.name")` might return `NULL` -> NPE.

2022-04-07 14:50 UTC, ylangisc approved these changes

2022-04-07 15:51 UTC, merged