Add profile for ArvanCloud ir-thr-at1(Tehran)
iterate-ch/cyberduck pull request #13280
Opened 2022-04-10 15:17 UTC by ehsantdy

ArvanCloud Object Storage goes beyond the limited traditional file storage. It gives you access to backup and archived files and allows sharing. Files like profile image in the app, images sent by users or scanned documents can be stored securely and easily in our Object Storage service.

2022-04-10 15:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=13280) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=13280) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iterate-ch/cyberduck?pullRequest=13280) it.</sub>

2022-04-14 13:20 UTC, AliveDevil requested changes

2022-04-17 06:44 UTC, ehsantdy commented
Thanks @AliveDevil

2022-04-24 11:54 UTC, AliveDevil approved these changes

2022-04-24 19:07 UTC, dkocher commented
Looks like this is a rather niche provider. Please provide the connection profile on your own website for customers. When downloaded it can be double clicked to open and register with Cyberduck and Mountain Duck.

2022-04-24 19:07 UTC, closed without merging