Feature/gh 13426
iterate-ch/cyberduck pull request #13427
Opened 2022-06-02 10:05 UTC by dkocher

2022-06-03 08:40 UTC, AliveDevil commented
Forbidden for Nextcloud.
![image](https://user-images.githubusercontent.com/734738/171820090-5f87f98e-5748-42f0-99b9-072533d088f4.png)

2022-06-03 12:39 UTC, dkocher commented
> Forbidden for Nextcloud. 

I cannot reproduce the failure here.

```
POST /ocs/v2.php/apps/files_sharing/api/v1/shares?path=sandbox&shareType=3&publicUpload=true HTTP/1.1
OCS-APIRequest: true
Accept: application/xml
Content-Length: 0
Host: cloud.iterate.ch
Connection: Keep-Alive
User-Agent: Cyberduck/null.null (Mac OS X/12.4) (aarch64)
Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; oc7vsmzhpklo=7hqpkfo1vi52pront5v876o5is; oc_sessionPassphrase=H0jhNhmjXh9k5rf0SYLfzyRo6cKa8Gz4tDYp4%2F7S34qC1FO7th%2BPnomCN6fCf07IrOnda54XC7Or05ctJr7zeNIN7LY8aRJZxkp%2FvA4bRSfDjcTFec7AH6byEzMQ6I%2F9
Accept-Encoding: gzip,deflate
Authorization: Basic ****=

HTTP/1.1 200 OK
Server: nginx/1.20.0
…
```

2022-06-07 08:56 UTC, dkocher commented
> Forbidden for Nextcloud. 

Added missing error handling in 8905e800.

2022-06-07 08:58 UTC, AliveDevil requested changes

2022-06-07 08:58 UTC, AliveDevil commented on nextcloud/src/test/java/ch/cyberduck/core/nextcloud/NextcloudShareProviderTest.java
> +    public void testToDownloadUrlPasswortTooShort() throws Exception {
```suggestion
    public void testToDownloadUrlPasswordTooShort() throws Exception {
```

2022-06-07 08:58 UTC, AliveDevil commented on nextcloud/src/test/java/ch/cyberduck/core/nextcloud/NextcloudShareProviderTest.java
> +    public void testToDownloadUrlPasswort() throws Exception {
```suggestion
    public void testToDownloadUrlPassword() throws Exception {
```

2022-06-07 08:58 UTC, AliveDevil commented on nextcloud/src/test/java/ch/cyberduck/core/nextcloud/NextcloudShareProviderTest.java
> +    public void testToUploadUrlPasswortTooShort() throws Exception {
```suggestion
    public void testToUploadUrlPasswordTooShort() throws Exception {
```

2022-06-08 15:27 UTC, merged