Implement versioning custom action.
iterate-ch/cyberduck pull request #13544
Opened 2022-07-05 16:22 UTC by ylangisc

2022-07-05 18:07 UTC, dkocher requested changes
Add integration test.

2022-07-06 05:27 UTC, ylangisc commented on ctera/src/main/java/ch/cyberduck/core/ctera/CteraCustomActionVersioning.java
> +        final String device = this.getDeviceName();
Yes, would be better.

2022-07-06 05:27 UTC, ylangisc commented on ctera/src/main/java/ch/cyberduck/core/ctera/CteraCustomActionVersioning.java
> +    private String getDeviceName() throws BackgroundException {
Done.

2022-07-06 05:28 UTC, ylangisc commented on ctera/src/main/java/ch/cyberduck/core/ctera/CteraCustomActionVersioning.java
> +            new DefaultLocalTouchFeature().touch(file);
Yes.

2022-07-06 06:31 UTC, dkocher requested changes

2022-07-06 06:31 UTC, dkocher commented on ctera/src/main/java/ch/cyberduck/core/ctera/CteraCustomActionVersioning.java
> +            throw new InteroperabilityException("No token or device found");
Throw _No token found in keychain_ when keychain returns null and _No device found_ when device array is empty.

2022-07-06 06:31 UTC, dkocher commented on ctera/src/test/java/ch/cyberduck/core/ctera/CteraCustomActionVersioningTest.java
> +        final Host host = new Host(new CteraProtocol(), "mountainduck.ctera.me", new Credentials(
Extract abstract test class like in other protocols for connection setup.

2022-07-06 13:25 UTC, dkocher approved these changes

2022-07-06 13:25 UTC, merged