Load profiles only once when tab is selected.
iterate-ch/cyberduck pull request #13590
Opened 2022-07-19 15:08 UTC by dkocher

2022-07-22 09:26 UTC, ylangisc commented
@AliveDevil Is there any change needed for Windows?

2022-07-22 09:38 UTC, AliveDevil commented
Profiles view in Cyberduck is already single-loaded (due to the Preferences window being singleton)
https://github.com/iterate-ch/cyberduck/blob/master/core/native/refresh/src/main/csharp/ViewModels/Preferences/Pages/ProfilesViewModel.cs#L51

On Mountain Duck the tab usually is loaded once it is activated, that is the tab is deselected, and reselected. With that flag it is only loaded once per lifetime of preferences-window.

So behavior, currently:
* On Cyberduck it is loaded once per App-lifetime
* On Mountain Duck everytime the preferences window is reopened and the profiles tab is selected, it gets refreshed

Should this be changed as well?

2022-07-26 05:44 UTC, ylangisc requested changes
As the available profiles don't change often, I would suggest to change it to once per App-lifetime for all our ducks. Same for macOS.

2022-07-26 12:11 UTC, AliveDevil commented
Updated behavior in Windows implementation. Uses central registry/cache which lazy-loads, once requested.

2022-07-26 12:11 UTC, AliveDevil commented
Going to create PR to fix failing Windows builds.

2022-07-27 09:34 UTC, AliveDevil commented
Rebased to fix Windows-build.

2022-07-27 12:07 UTC, ylangisc requested changes
As mentioned in https://github.com/iterate-ch/cyberduck/pull/13590#pullrequestreview-1050392593 the macOS part loading it once only per app lifetime is missing.

2022-07-30 16:01 UTC, dkocher commented on core/native/refresh/src/main/csharp/Services/ProfilesProvider.cs
> +            public override void cleanup(object result) => completionSource.SetResult(Utils.ConvertFromJavaList<ProfileDescription>((java.util.Collection)result));
On a network failure the `result` will be a set of profiles installed locally only. Thus it should not be cached.

2022-07-30 16:02 UTC, dkocher commented
> As mentioned in [#13590 (review)](https://github.com/iterate-ch/cyberduck/pull/13590#pullrequestreview-1050392593) the macOS part loading it once only per app lifetime is missing.

On a network failure the `result` of the `ProfilesSynchronizeWorker` will be a set of profiles installed locally only. Thus it should run once when opening a _Preferences_ window.

2022-08-01 10:10 UTC, AliveDevil commented
Then we should provide a separate cache for profiles (independent of client), and running ProfilesSynchronizeWorker everytime - doing a noop if one ProfilesSynchronizeWorker previously registered a successful remote listing.

2022-08-13 14:50 UTC, dkocher commented
> Then we should provide a separate cache for profiles (independent of client), and running ProfilesSynchronizeWorker everytime - doing a noop if one ProfilesSynchronizeWorker previously registered a successful remote listing.

I don't see much benefit of having a cache with a longer lifespan than the _Preferences_ window controller. It is fine to reload in this case.

2022-08-18 08:29 UTC, ylangisc approved these changes

2022-08-18 08:29 UTC, merged