CBC based ciphers are considered to be weak and thus not enabled by d…
iterate-ch/cyberduck pull request #14204
Opened 2023-02-07 09:31 UTC by ylangisc

…efault in OpenSSH using OpenSSL 3.

2023-02-07 10:10 UTC, ylangisc commented
https://github.com/proftpd/proftpd/issues/1595

2023-02-09 09:46 UTC, dkocher requested changes

2023-02-09 09:46 UTC, dkocher commented on ssh/src/main/java/ch/cyberduck/core/sftp/SFTPSession.java
> +        final List<Named<Cipher>> reordered = new ArrayList<>();
Sort existing list instead using comparator.

2023-02-13 10:09 UTC, dkocher approved these changes

2023-02-13 10:34 UTC, merged