Make sure an agent is running before adding it as authentication method.
iterate-ch/cyberduck pull request #14205
Opened 2023-02-07 13:39 UTC by ylangisc

Fixes #14196.

2023-02-09 09:55 UTC, dkocher requested changes

2023-02-09 09:55 UTC, dkocher commented on ssh/src/main/java/ch/cyberduck/core/sftp/SFTPSession.java
>                  case windows:
These checks are redundant it seems if proper checks for agent to be available in implementation for `getIdentities`

2023-02-09 09:55 UTC, dkocher commented on ssh/src/main/java/ch/cyberduck/core/sftp/auth/AgentAuthenticator.java
> +    public boolean isAvailable() {
Move this check instead to `getIdentities` of implementations.

2023-02-14 14:38 UTC, dkocher approved these changes

2023-02-14 15:37 UTC, merged

2023-02-19 22:20 UTC, blaineam reviewed
This PR broke Mountain Duck for my 1Password 8 SSH setup. I'm pretty sure the section that broke it is the commented block.

2023-02-19 22:20 UTC, blaineam commented on ssh/src/main/java/ch/cyberduck/core/sftp/openssh/OpenSSHAgentAuthenticator.java
> +        if(!proxy.isRunning()) {
I think this additional conditional is breaking 1password for non IdentityFile uses. I don't think this check is needed for the original issue either.