Add support for new GCM encryption based vaults as of Cryptomator 1.7.
iterate-ch/cyberduck pull request #14213
Opened 2023-02-09 14:45 UTC by ylangisc

2023-02-09 15:47 UTC, dkocher requested changes
Fix test failures.

2023-02-11 04:25 UTC, sheekk requested changes

2023-02-11 04:25 UTC, sheekk commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/features/CryptoChecksumCompute.java
>              // Make nonces reusable in case we need to compute a checksum
hfseyn

2023-02-11 04:25 UTC, sheekk commented on box/src/test/java/ch/cyberduck/core/cryptomator/BufferWriteFeatureTest.java
>          writeStatus.setHeader(cryptomator.getFileHeaderCryptor().encryptHeader(header));
httiojhd

2023-02-11 04:25 UTC, sheekk commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/CryptoVault.java
>  import ch.cyberduck.core.exception.BackgroundException;
tijbbhcc.com

2023-02-11 04:25 UTC, sheekk commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/features/CryptoCopyFeature.java
>              // Write header to be reused in writer
glllmvzg

v
hctu

2023-02-11 04:25 UTC, sheekk commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/features/CryptoDirectoryV6Feature.java
>          status.setHeader(vault.getFileHeaderCryptor().encryptHeader(header));
gjbcfh.nfyjj

2023-02-11 04:25 UTC, sheekk commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/features/CryptoDirectoryV7Feature.java
>          // Write header
wppp

2023-02-11 04:25 UTC, sheekk commented on cryptomator/src/test/java/ch/cyberduck/core/cryptomator/CryptoChecksumComputeTest.java
>          final Path file = new Path(vault, "f", EnumSet.of(Path.Type.file));
kvcduk

2023-02-11 04:25 UTC, sheekk commented on cryptomator/src/test/java/ch/cyberduck/core/cryptomator/CryptoOutputStreamTest.java
>          final CryptoVault vault = this.getVault();
finy

2023-02-11 04:25 UTC, sheekk commented on cryptomator/src/test/java/ch/cyberduck/core/cryptomator/CryptoVaultTest.java
>  import ch.cyberduck.core.TestProtocol;
iooppp

2023-02-11 04:25 UTC, sheekk commented on cryptomator/src/test/java/ch/cyberduck/core/cryptomator/random/RotatingNonceGeneratorTest.java
>      @Test
ppou

2023-02-11 04:25 UTC, sheekk commented on dropbox/src/test/java/ch/cyberduck/core/cryptomator/DropboxWriteFeatureTest.java
>          final CryptoWriteFeature<Metadata> writer = new CryptoWriteFeature<>(session, new DropboxWriteFeature(session), cryptomator);
mvcswhokxgu

2023-02-11 04:25 UTC, sheekk commented on eue/src/test/java/ch/cyberduck/core/cryptomator/EueWriteFeatureTest.java
>          final FileHeader header = cryptomator.getFileHeaderCryptor().create();
hhhvbni
mkloyrdvb

jjiutd

2023-02-11 04:25 UTC, sheekk commented on googledrive/src/test/java/ch/cyberduck/core/cryptomator/DriveWriteFeatureTest.java
>          final CryptoWriteFeature<File> writer = new CryptoWriteFeature<>(session, new DriveWriteFeature(session, fileid), cryptomator);
bgfdrtuijh@jkgf@hu

2023-02-11 04:25 UTC, sheekk commented on openstack/src/test/java/ch/cyberduck/core/cryptomator/SwiftWriteFeatureTest.java
>          status.setHeader(cryptomator.getFileHeaderCryptor().encryptHeader(header));
cfrgujuhfrㅎㄹㅇㅇ

2023-02-11 04:25 UTC, sheekk commented on s3/src/test/java/ch/cyberduck/core/cryptomator/S3MultipartWriteFeatureTest.java
> -        writeStatus.setNonces(new RandomNonceGenerator());
ㅠㅍㅊㄹㄹ쇼ㅕfrtyggfddr

2023-02-11 04:25 UTC, sheekk commented on s3/src/test/java/ch/cyberduck/core/cryptomator/S3VersioningFeatureTest.java
>          final Write<StorageObject> writer = new CryptoWriteFeature<>(session, new S3MultipartWriteFeature(session, new S3AccessControlListFeature(session)), cryptomator);
bhhuytddfghhfffghh

2023-02-11 04:25 UTC, sheekk commented on s3/src/test/java/ch/cyberduck/core/cryptomator/S3WriteFeatureTest.java
>          final FileHeader header = cryptomator.getFileHeaderCryptor().create();
kjhfetyijnbbcsakklppi@hgd@h

2023-02-11 04:25 UTC, sheekk commented on ssh/src/test/java/ch/cyberduck/core/cryptomator/SFTPReadFeatureTest.java
> -        status.setNonces(new RandomNonceGenerator());
joiiijhgfvbnjkkhf

2023-02-11 04:25 UTC, sheekk commented on ssh/src/test/java/ch/cyberduck/core/cryptomator/SFTPWriteFeatureTest.java
>          final FileHeader header = cryptomator.getFileHeaderCryptor().create();
grrtyikjnbvdset@jhfd

2023-02-11 04:25 UTC, sheekk commented on webdav/src/test/java/ch/cyberduck/core/cryptomator/CryptoDAVSingleTransferWorkerTest.java
> -        status.setNonces(new RotatingNonceGenerator(cryptomator.numberOfChunks(content.length)));
jjhhjhuy@jhbvxdryuuh

2023-02-11 04:25 UTC, sheekk commented on webdav/src/test/java/ch/cyberduck/core/cryptomator/DAVReadFeatureTest.java
>          status.setChecksum(writer.checksum(test, status).compute(new ByteArrayInputStream(content), status));
uttujhferggggghj@jh

2023-02-11 04:25 UTC, sheekk commented on backblaze/src/test/java/ch/cyberduck/core/cryptomator/B2LargeUploadWriteFeatureTest.java
>          writeStatus.setHeader(cryptomator.getFileHeaderCryptor().encryptHeader(header));
uiiv@ghjoooplfftvb
ufe[nvc]()

2023-02-11 04:25 UTC, sheekk commented on azure/src/test/java/ch/cyberduck/core/cryptomator/AzureWriteFeatureTest.java
>          final FileHeader header = cryptomator.getFileHeaderCryptor().create();
- [ ] - _hcnju[fuilnfb@geghcvjfdfhv****]()_

2023-02-11 04:25 UTC, sheekk commented on box/src/test/java/ch/cyberduck/core/cryptomator/BoxWriteFeatureTest.java
>          final StatusOutputStream out = feature.write(test, writeStatus, new DisabledConnectionCallback());
kuu@[gfcj[fsrgv_fjc_]()]()

2023-02-13 13:07 UTC, dkocher requested changes

2023-02-13 13:07 UTC, dkocher commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/CryptoVault.java
> +                throw new VaultException("Invalid JWT signature");
Include cause to preserve stacktrace.

2023-02-13 13:07 UTC, dkocher commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/CryptoVault.java
> +                throw new VaultException(String.format("Expected vault config for version %d", expectedVaultVersion));
Include cause to preserve stacktrace.

2023-02-13 13:07 UTC, dkocher commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/CryptoVault.java
> +                throw new VaultException(String.format("Failed to verify vault config %s", token));
Include cause to preserve stacktrace.

2023-02-13 13:07 UTC, dkocher commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/CryptoVault.java
> +            switch(vaultConfig.cipherCombo) {
Move to `VaultConfig` allowing to query for nonce size?

2023-02-14 16:01 UTC, dkocher approved these changes

2023-02-14 16:08 UTC, merged