Fill byte array with null values until buffer length in case we read …
iterate-ch/cyberduck pull request #14319
Opened 2023-03-07 13:27 UTC by ylangisc

…over file length.

2023-03-07 15:31 UTC, dkocher requested changes

2023-03-07 15:31 UTC, dkocher commented on core/src/main/java/ch/cyberduck/core/io/FileBuffer.java
> +                System.arraycopy(new byte[available], 0, chunk, read, missing);
Last parameter should be `available`?

2023-03-08 07:39 UTC, ylangisc commented
Reuse of buffer after closing it is no longer possible (`write` after `close`). Refer to `ec67f66f9f7e6c0a9ecfc58e9ae22a5db46b96ba` in Mountain Duck.

2023-03-08 11:04 UTC, dkocher approved these changes

2023-03-08 11:43 UTC, merged