SMB Session
iterate-ch/cyberduck pull request #14597
Opened 2023-04-30 09:24 UTC by mbscit

2023-04-30 09:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=14597) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=14597) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: oaehmka<br/>:x: mbscit<br/><hr/>**oaehmka** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iterate-ch/cyberduck?pullRequest=14597) it.</sub>

2023-04-30 15:10 UTC, dkocher requested changes
- Add implementation of `AbstractExceptionMappingService<SMBApiException>` mapping errors to various subclasses of `BackgroundException`.

2023-04-30 15:10 UTC, dkocher commented on smb/pom.xml
> +        <version>8.5.7-SNAPSHOT</version>
Fix parent version.

2023-05-01 08:03 UTC, ylangisc reviewed
* consistent use of `final` for method parameters and local variables
* would be great to concentrate on writing tests as a next step

2023-05-15 09:29 UTC, AliveDevil commented
This is superseded by #14672?

2023-05-17 12:09 UTC, closed without merging