Add preference for "Save in Keychain" when unlocking vaults
iterate-ch/cyberduck pull request #14662
Opened 2023-05-11 09:44 UTC by dkocher

Fix #11694.

2023-05-15 08:14 UTC, AliveDevil requested changes
What's the state here[^1]?
[^1]: https://github.com/iterate-ch/cyberduck/blob/465be7018aeeca4dc2bf6161d9ce83824460004c/core/src/main/java/ch/cyberduck/core/vault/VaultCredentials.java#LL30C50-L30C51

There is conflicting/duplicate usage now on "cryptomator.keychain" and "vault.keychain".

2023-05-15 08:14 UTC, AliveDevil commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/CryptoVault.java
> +                            .keychain(preferences.getBoolean("cryptomator.keychain"))
We already have "vault.keychain"[^1]
[^1]: https://github.com/iterate-ch/cyberduck/blob/465be7018aeeca4dc2bf6161d9ce83824460004c/cryptomator/src/main/java/ch/cyberduck/core/cryptomator/CryptoVault.java#LL286C75-L286C75

2023-05-19 08:32 UTC, AliveDevil approved these changes

2023-05-22 07:23 UTC, ylangisc approved these changes

2023-05-22 07:24 UTC, merged