SMB Features
iterate-ch/cyberduck pull request #14672
Opened 2023-05-12 21:36 UTC by mbscit

2023-05-12 21:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=14672) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/iterate-ch/cyberduck?pullRequest=14672) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: oaehmka<br/>:x: mbscit<br/><hr/>**oaehmka** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iterate-ch/cyberduck?pullRequest=14672) it.</sub>

2023-05-13 20:26 UTC, dkocher requested changes

2023-05-13 20:26 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBReadFeature.java
> +            throw new SmbExceptionMappingService().map(e);
```suggesetion
            throw new SmbExceptionMappingService().map("Download {0} failed", e, file);
```

2023-05-13 20:26 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBWriteFeature.java
> +            throw new SmbExceptionMappingService().map(e);
```suggestion
            throw new SmbExceptionMappingService().map("Upload {0} failed", e, file);
```

2023-05-13 20:26 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBAttributesFinderFeature.java
> +            throw new SmbExceptionMappingService().map(e);
```suggestion
            throw new SmbExceptionMappingService().map("Failure to read attributes of {0}", e, file);
```

2023-05-13 20:26 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBReadFeature.java
> +        private File file;
Add `final`

2023-05-13 20:26 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBWriteFeature.java
> +        private File file;
Add `final`

2023-05-30 08:52 UTC, dkocher requested changes

2023-05-30 08:52 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBCopyFeature.java
> +            throw new BackgroundException(e);
Replace with parameters `"Cannot copy {0}", e, source`

```suggestion
            throw new BackgroundException("Cannot copy {0}", e, source);
```

2023-05-30 08:52 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBCopyFeature.java
> +            throw new SMBExceptionMappingService().map(e);
Replace with parameters `"Cannot copy {0}", e, source`

```suggestion
            throw new BackgroundException("Cannot copy {0}", e, source);
```

2023-05-30 08:52 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBListService.java
> +            throw new SMBExceptionMappingService().map(e);
Replace with parameters `"Listing directory {0} failed", e, directory`

```suggestion
            throw new SMBExceptionMappingService().map("Listing directory {0} failed", e, directory);
```

2023-06-02 21:31 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBTimestampFeature.java
> +            throw new SMBExceptionMappingService().map("Setting timestamp on file {0} failed", e, file);
Use localized text `Cannot change timestamp of {0}`

```suggestion
            throw new SMBExceptionMappingService().map("Cannot change timestamp of {0}", e, file);
```

2023-06-27 13:09 UTC, dkocher requested changes
- [ ] Sqash commits
- [ ] Review comments
- [ ] Resolve TODOs

2023-06-27 13:09 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBProtocol.java
> +public class SMBProtocol extends AbstractProtocol {
Override `getUsernamePlaceholder` to provide placeholder text with username format requiring share name.

2023-06-27 13:09 UTC, dkocher commented on smb/src/main/java/ch/cyberduck/core/smb/SMBReadFeature.java
> +    private final class SMBInputStream extends ProxyInputStream {
Make static.

2023-07-16 09:01 UTC, dkocher requested changes
- [ ] Sqash commits
- [ ] Review comments
- [ ] Resolve TODOs

2023-08-16 21:59 UTC, mbscit commented
We have opened a new PR with all comments resolved and the commits squashed
[https://github.com/iterate-ch/cyberduck/pull/15006](https://github.com/iterate-ch/cyberduck/pull/15006
)

2023-08-16 21:59 UTC, closed without merging