Add support to pass creation date in feature
iterate-ch/cyberduck pull request #15101
Opened 2023-09-07 15:37 UTC by dkocher

2023-09-13 08:00 UTC, ylangisc requested changes

2023-09-13 08:00 UTC, ylangisc commented on s3/src/main/java/ch/cyberduck/core/s3/S3MetadataFeature.java
Also add creation date. `btime` to be interoperable with rclone. Refer to https://rclone.org/docs/.

2023-09-13 08:00 UTC, ylangisc commented on s3/src/main/java/ch/cyberduck/core/s3/S3WriteFeature.java
Add creation date.

2023-09-13 08:00 UTC, ylangisc commented on backblaze/src/main/java/ch/cyberduck/core/b2/B2WriteFeature.java
To set the creation date we could add a custom `X-Bz-Info-*` header, e.g. `X-Bz-Info-src_creation_date_millis`. Refer to https://www.backblaze.com/apidocs/b2-upload-file

> X-Bz-Info-*
The * part of the header name is replaced with the name of a custom field in the file information stored with the file, and the value is an arbitrary UTF-8 string, percent-encoded. The same info headers sent with the upload will be returned with the download. The header name is case insensitive.

2023-09-13 08:00 UTC, ylangisc commented on box/src/main/java/ch/cyberduck/core/box/BoxWriteFeature.java
Add `contentCreatedAt`.

2023-09-13 08:00 UTC, ylangisc commented on core/src/main/java/ch/cyberduck/core/transfer/copy/AbstractCopyFilter.java
>          if(options.timestamp) {
Should we also allow extend `options` to allow setting the creation date?

2023-09-13 08:00 UTC, ylangisc commented on core/src/main/java/ch/cyberduck/core/worker/WriteTimestampWorker.java
Not sure if `created` should be part of `equals` and `hashCode` implementation.

2023-09-13 08:00 UTC, ylangisc commented on dracoon/src/main/java/ch/cyberduck/core/sds/SDSDirectS3UploadFeature.java
Add `timestampCreation`.

2023-09-13 08:00 UTC, ylangisc commented on dracoon/src/main/java/ch/cyberduck/core/sds/SDSUploadService.java
Add creation date.

2023-09-13 08:00 UTC, ylangisc commented on eue/src/main/java/ch/cyberduck/core/eue/EueUploadHelper.java
Add creation date.

2023-09-13 08:00 UTC, ylangisc commented on googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveTimestampFeature.java
Add `setCreatedDate`.

2023-09-13 08:00 UTC, ylangisc commented on googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveWriteFeature.java
Add `setCreatedDate`.

2023-09-13 08:00 UTC, ylangisc commented on googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageCopyFeature.java
Add `setTimeCreated`.

2023-09-13 08:00 UTC, ylangisc commented on googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageTimestampFeature.java
Add `setTimeCreated`.

2023-09-13 08:00 UTC, ylangisc commented on googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageWriteFeature.java
Add `setTimeCreated`.

2023-09-13 08:00 UTC, ylangisc commented on nextcloud/src/main/java/ch/cyberduck/core/nextcloud/NextcloudWriteFeature.java
Add `X-OC-CTime` header.

2023-09-13 08:00 UTC, ylangisc commented on nio/src/main/java/ch/cyberduck/core/nio/LocalTimestampFeature.java
Add creation date.

2023-09-13 08:00 UTC, ylangisc commented on storegate/src/main/java/ch/cyberduck/core/storegate/StoregateWriteFeature.java
>              meta.setCreated(DateTime.now());
Use creation date from `TransferStatus`.

2023-09-13 08:00 UTC, ylangisc commented on webdav/src/main/java/ch/cyberduck/core/dav/DAVTimestampFeature.java
Add custom properties for creation date too?

2023-09-19 22:07 UTC, dkocher commented on googledrive/src/main/java/ch/cyberduck/core/googledrive/DriveTimestampFeature.java
fieldNotWritable

2023-09-20 11:56 UTC, dkocher commented on googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageWriteFeature.java
Non-editable metadata in Google Storage

2023-09-20 11:56 UTC, dkocher commented on googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageTimestampFeature.java
Non-editable metadata

2023-09-20 11:56 UTC, dkocher commented on googlestorage/src/main/java/ch/cyberduck/core/googlestorage/GoogleStorageCopyFeature.java
Non-editable metadata

2023-09-22 07:05 UTC, ylangisc commented
@dkocher Pending comment: https://github.com/iterate-ch/cyberduck/pull/15101/files/c29d5586b38b31dddfb6f5e79ba54b0b6f38c233#r1324129083

2023-09-22 14:00 UTC, dkocher commented on webdav/src/main/java/ch/cyberduck/core/dav/DAVTimestampFeature.java
No priority.

2023-09-25 14:03 UTC, merged