Factory for STSAssumeRoleCredentialsRequestInterceptor to inject implementations extending the interceptor
iterate-ch/cyberduck pull request #15178
Opened 2023-10-05 12:46 UTC by chenkins

Fixes #15177.

2023-10-05 15:23 UTC, dkocher requested changes

2023-10-05 15:23 UTC, dkocher commented on s3/src/main/java/ch/cyberduck/core/sts/STSAssumeRoleAuthorizationService.java
> +        if(StringUtils.isBlank(preferences.getProperty("s3.assumerole.tokentype")) || preferences.getProperty("s3.assumerole.tokentype").equals("id_token")) {
Provide default in `default.properties` and omit check for property definition.

2023-10-05 15:23 UTC, dkocher commented on s3/src/main/java/ch/cyberduck/core/sts/STSAssumeRoleAuthorizationService.java
> +        if(StringUtils.isBlank(preferences.getProperty("s3.assumerole.tokentype")) || preferences.getProperty("s3.assumerole.tokentype").equals("id_token")) {
Can this be moved into a single pull request.

2023-10-06 06:28 UTC, ylangisc commented on s3/src/main/java/ch/cyberduck/core/sts/STSAssumeRoleAuthorizationService.java
Formatting.

2023-10-06 08:09 UTC, dkocher commented
What features are missing in the implementations that require the ability to subclass or inject different implementations?

2023-10-09 15:03 UTC, chenkins commented on s3/src/main/java/ch/cyberduck/core/sts/STSAssumeRoleAuthorizationService.java
done.

2023-10-19 17:25 UTC, dkocher commented
I propose #15227 instead.

2023-10-20 19:20 UTC, closed without merging