TCP reachability implementation
iterate-ch/cyberduck pull request #15249
Opened 2023-10-23 16:38 UTC by dkocher

2023-10-30 17:29 UTC, ylangisc commented on core/src/test/java/ch/cyberduck/core/diagnostics/HttpReachabilityTest.java
> +        assertTrue(r.isReachable(
Same test as in the line before.

2023-10-30 17:31 UTC, ylangisc commented on core/src/main/csharp/ch/cyberduck/core/diagnostics/TcpReachability.cs
File can be deleted?

2023-10-30 17:38 UTC, ylangisc commented on core/dylib/src/test/java/ch/cyberduck/core/diagnostics/SystemConfigurationReachabilityTest.java
What's the reason for the ignored tests?

2023-10-30 19:33 UTC, dkocher commented on core/dylib/src/test/java/ch/cyberduck/core/diagnostics/SystemConfigurationReachabilityTest.java
Still registered and required for NetworkChangeMonitor.

2023-11-07 12:52 UTC, ylangisc requested changes
See comments.

2023-11-07 14:11 UTC, ylangisc approved these changes

2023-11-08 07:32 UTC, merged