Update runtime dependency.
iterate-ch/cyberduck pull request #15287
Opened 2023-10-29 19:07 UTC by dkocher

2023-10-30 07:53 UTC, ylangisc requested changes
GitHub workflow files need to be adjusted too.

2023-10-30 13:10 UTC, dkocher commented
> GitHub workflow files need to be adjusted too.

The runtime is managed separately from the build JDK.

2023-10-30 16:19 UTC, ylangisc commented
> > GitHub workflow files need to be adjusted too.
> 
> The runtime is managed separately from the build JDK.

Referring to https://github.com/iterate-ch/cyberduck/blob/master/.github/workflows/build.yml#L21

2024-11-15 16:47 UTC, ylangisc approved these changes

2024-11-15 16:47 UTC, merged