Allow for vault factory with null arguments.
iterate-ch/cyberduck pull request #15545
Opened 2024-01-16 17:52 UTC by chenkins

2024-01-16 22:43 UTC, dkocher approved these changes

2024-01-17 06:50 UTC, ylangisc reviewed
The `null` parameters when calling the factory could be hidden by adding a second getter to the factory.

2024-01-17 07:20 UTC, dkocher requested changes
As @ylangisc suggested it would be better to provide an additional factory method with different parameters. Would return `Vault.DISABLED` or throw `FactoryException` when the implementation does not support the constructor.

2024-01-17 13:21 UTC, dkocher approved these changes

2024-01-17 15:43 UTC, ylangisc approved these changes

2024-01-17 15:43 UTC, merged