Fix ctera touch preflight.
iterate-ch/cyberduck pull request #15956
Opened 2024-05-23 16:10 UTC by chenkins

2024-05-23 16:12 UTC, dkocher commented
Obsoletes #15854.

2024-05-23 16:51 UTC, dkocher requested changes
Squash commits.

2024-05-24 06:02 UTC, dkocher approved these changes

2024-06-03 08:55 UTC, ylangisc approved these changes

2024-06-03 08:55 UTC, merged