Feature/ctera acl update documenation
iterate-ch/cyberduck pull request #15960
Opened 2024-05-25 11:04 UTC by chenkins

2024-05-25 11:07 UTC, chenkins commented
Depends on #15956

2024-05-27 12:17 UTC, ylangisc approved these changes

2024-05-27 13:59 UTC, dkocher requested changes

2024-05-27 13:59 UTC, dkocher commented on ctera/src/main/java/ch/cyberduck/core/ctera/README.md
> +## Preflight Checks (nfs 4.x)
Preflight checks apply to all connect modes not dependent on filesystem driver.

2024-05-27 13:59 UTC, dkocher commented on ctera/src/main/java/ch/cyberduck/core/ctera/README.md
> +### macOS File Provider Capabilities (mode integrated) 5.x
```suggestion
### macOS File Provider Capabilities (_Integrated_ connect mode) Mountain Duck 5+
```

2024-05-27 13:59 UTC, dkocher commented on ctera/src/main/java/ch/cyberduck/core/ctera/README.md
> +### Windows CBFS API (mode sync) and Cloud Files API (mode integrated) (5.x)
```suggestion
### Windows CBFS API (_Online_ and _Smart Synchronization_ connect mode) and Cloud Files API (_Integrated_ connect mode) Mountain Duck 5+
```

2024-06-03 08:57 UTC, ylangisc approved these changes

2024-07-04 21:00 UTC, dkocher requested changes
It looks to me there is a lot of duplication. It would suffice to sumarize the mapping to POSIX & FileSystemRights model and detail how dynamic preflight checks are used for filesystem operations.

2024-07-08 18:33 UTC, chenkins commented
Superseded by #16111

2024-07-08 18:33 UTC, closed without merging