Fix install -DskipSign -DskipNotarize.
iterate-ch/cyberduck pull request #16100
Opened 2024-07-02 14:31 UTC by chenkins

2024-07-02 15:50 UTC, dkocher requested changes

2024-07-02 15:50 UTC, dkocher commented on cli/osx/build.xml
>          <exec executable="/usr/bin/xcrun" failonerror="true">
This will fail when above tasks are skipped.

2024-07-03 08:11 UTC, dkocher approved these changes

2024-07-05 09:06 UTC, ylangisc approved these changes

2024-07-05 09:07 UTC, merged