Review permissions for boxes
iterate-ch/cyberduck pull request #16234
Opened 2024-08-15 09:53 UTC by dkocher

2024-08-16 06:54 UTC, chenkins requested changes
Add test coverage.

2024-08-16 06:54 UTC, chenkins commented on deepbox/src/main/java/ch/cyberduck/core/deepbox/DeepboxListService.java
> +                            new PathAttributes().withHidden(true));
Add test coverage.

2024-08-16 06:54 UTC, chenkins commented on deepbox/src/main/java/ch/cyberduck/core/deepbox/DeepboxPathContainerService.java
> +        if(this.isDeepbox(file)) {
```suggestion
        if(!file.isDirectory()) {
            return false;
        }
        if(this.isDeepbox(file)) {
```

2024-08-16 09:00 UTC, chenkins approved these changes
Lgtm. Remove non-necessary code comments.

2024-08-16 09:00 UTC, chenkins commented on deepbox/src/test/java/ch/cyberduck/core/deepbox/DeepboxListServiceTest.java
> +        assertNotSame(AttributedList.EMPTY, new DeepboxListService(session, nodeid).list(trash, new DisabledListProgressListener())); // assert no fail
```suggestion
        assertNotSame(AttributedList.EMPTY, new DeepboxListService(session, nodeid).list(trash, new DisabledListProgressListener()));
```

2024-08-16 09:00 UTC, chenkins commented on deepbox/src/test/java/ch/cyberduck/core/deepbox/DeepboxListServiceTest.java
>          // assert no fail
```suggestion
```

2024-08-26 07:58 UTC, dkocher commented on deepbox/src/test/java/ch/cyberduck/core/deepbox/DeepboxListServiceTest.java
> +        assertNotSame(AttributedList.EMPTY, new DeepboxListService(session, nodeid).list(trash, new DisabledListProgressListener())); // assert no fail
Comment still valid.

2024-08-26 07:58 UTC, dkocher commented on deepbox/src/test/java/ch/cyberduck/core/deepbox/DeepboxListServiceTest.java
>          // assert no fail
Comment still valid.

2024-08-26 11:42 UTC, ylangisc approved these changes

2024-08-26 11:43 UTC, merged