First ideas for uvf imple.
iterate-ch/cyberduck pull request #16623
Opened 2024-12-06 15:44 UTC by chenkins

2025-02-27 12:37 UTC, chenkins commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/AbstractVault.java
> +    private static final Pattern BASE64URL_PATTERN = Pattern.compile("^([A-Za-z0-9_=-]+).c9r");
@ylangisc should be configurable for UVF.

2025-03-05 16:06 UTC, dkocher reviewed
- [ ] Should destroy master key when closing vault.
- [ ] Ensure master key is loaded in `load` only using password callback and not passed in constructor.

2025-03-06 07:38 UTC, dkocher requested changes
- [ ] Should destroy master key when closing vault.
- [x] Ensure master key is loaded in `load` only using password callback and not passed in constructor.

2025-03-08 13:41 UTC, chenkins commented on s3/src/test/java/ch/cyberduck/core/cryptomator/UVFTest.java
> +                assertTrue(Arrays.toString(list.toArray()), list.contains(new Path("/cyberduckbucket/subdir", EnumSet.of(AbstractPath.Type.directory, AbstractPath.Type.placeholder, AbstractPath.Type.
@dkocher @ylangisc the path comes without directory ID; when listing the subdir below, the call fails when encrytping the plain name. Is something missing in the UVF implementation or is there something missing in my test?

2025-03-09 16:37 UTC, ylangisc commented on s3/src/test/java/ch/cyberduck/core/cryptomator/UVFTest.java
> +                assertTrue(Arrays.toString(list.toArray()), list.contains(new Path("/cyberduckbucket/subdir", EnumSet.of(AbstractPath.Type.directory, AbstractPath.Type.placeholder, AbstractPath.Type.
In 01539ae.

2025-03-09 21:18 UTC, chenkins commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/impl/CryptoDirectoryUVFProvider.java
> +            }
@ylangisc what's the best approach - should we cache the revisions per directory along with its ID?

2025-03-09 21:21 UTC, chenkins commented on s3/src/test/java/ch/cyberduck/core/cryptomator/UVFTest.java
> +                assertEquals(1, list.size());
@ylangisc with the `loadRevision` workaround, the encryption part of the subdir works and the raw folder is listed remotely, but then fails in `AbstractVault.decrypt` when attemptyting to decrypt the file name, probably due to the file name decryptor statically linked to the initial revision. Need to continue there.

2025-03-10 06:48 UTC, ylangisc commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/impl/CryptoDirectoryUVFProvider.java
> +            // TODO can we not use org.cryptomator.cryptolib.v3.DirectoryContentCryptorImpl.decryptDirectoryMetadata()? DirectoryMetadataImpl is not visible and DirectoryMetadata is empty interface,
Use `DirectoryMetadataImpl#cast`.

2025-03-13 06:04 UTC, overheadhunter commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/impl/CryptoDirectoryUVFProvider.java
> +            // TODO can we not use org.cryptomator.cryptolib.v3.DirectoryContentCryptorImpl.decryptDirectoryMetadata()? DirectoryMetadataImpl is not visible and DirectoryMetadata is empty interface,
You mean the `dir.uvf` file? I considered it an implementation detail that should not be public.

2025-06-17 10:46 UTC, dkocher requested changes

2025-06-17 10:46 UTC, dkocher commented on cryptomator/src/main/java/ch/cyberduck/core/cryptomator/UVFVault.java
> +        throw new UnsupportedOperationException();
Missing implementation.

2025-06-19 13:18 UTC, chenkins commented
Superseded by https://github.com/iterate-ch/cyberduck/pull/17173

2025-06-19 13:18 UTC, closed without merging